#1215shinyapp折线图
##server部分
options(warn=-1)
library(shiny)
library(ggplot2)
library(showtext)
library(scales)
library("latex2exp")
library(plyr)
library(grid)
showtext.auto(enable=T)

pfun2=function(pc,pg,tot,country1,country2){
  options(warn=-1)
  tmp1=pc[pc$Country.code==country1,]
  tmp2=pg[pg$Country.code==country1,]
  tmp3=tot[tot$Country.code==country1,]
  con1=data.frame(x=rep(1990:2008,3),y=c(as.numeric(tmp1[1,3:21]),as.numeric(tmp2[1,3:21]),as.numeric(tmp3[1,3:21])),fill=rep(c("每GDP二氧化碳排放量","人均二氧化碳排放量","二氧化碳排放总量"),each=19),con=country1)
  tmp1=pc[pc$Country.code==country2,]
  tmp2=pg[pg$Country.code==country2,]
  tmp3=tot[tot$Country.code==country2,]
  con2=data.frame(x=rep(1990:2008,3),y=c(as.numeric(tmp1[1,3:21]),as.numeric(tmp2[1,3:21]),as.numeric(tmp3[1,3:21])),fill=rep(c("每GDP二氧化碳排放量","人均二氧化碳排放量","二氧化碳排放总量"),each=19),con=country2)
  tmp=rbind(con1,con2)
  ph=ggplot(data=tmp)+
    geom_point(aes(x=x,y=y,color=con))+
    geom_line(aes(x=x,y=y,color=con))+
    labs(x="",y="",color="国家")+
    scale_color_manual(values=c("red","blue"))+
    theme_bw()+
    theme(panel.grid=element_blank(),
          axis.text=element_text(size=10),
          legend.position="top",
          legend.title=element_text(size=15),
          legend.text=element_text(size=10))+
    facet_wrap(~fill,ncol=1,scales="free_y")
  print(ph)
}

shinyServer(function(input,output){
  output$plot=renderPlot(pfun2(pc1,pg1,tot1,input$con1,input$con2))
})
