#1215shinyapp折线图
##ui部分
options(warn=-1)
library(shiny)
library(ggplot2)
library(showtext)
library(scales)
library("latex2exp")
library(plyr)
library(grid)
showtext.auto(enable=T)
load("name_con.rda")

shinyUI(fluidPage(
  titlePanel("两国比较"),
  selectInput("con1","国家一",name_con),
  selectInput("con2","国家二",name_con),
  plotOutput("plot",height=500,width=700)
))